Feature/test edit update clear all
enionsouza/TODO-List pull request #15
Opened 2021-08-26 20:34 UTC by enionsouza

### Testing To Do list: part 2

In this milestone, created `todo-integration.test.js` to test the following functionalities: 
- [x] editing a task description.
- [x] updating an item's 'completed' status.
- [x] updating an item's index value upon drag/drop actions.
- [x] "Clear all completed" function.

To do so, we used Jest and Puppeteer libraries.

2021-08-26 21:08 UTC, henatan99 requested changes
Hi @enionsouza , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-26 21:08 UTC, henatan99 commented on src/spec/todo-integration.test.js
> +    const browser = await puppeteer.launch();
- [x] I think you can make use of the `jest` testing library mock functions to mock DOM elements instead of using `puppeteer`. Your tests work very well but in the project requirement, it is asked to use the `jest` testing library. You can see the example below on how to use a jest mock function.
``` 
import taskformDiv from '../../src/views1/taskform';

function isElement(element) {
  return element instanceof Element || element instanceof HTMLDocument;
}

let spy;
beforeAll(() => {
  spy = jest.spyOn(document, 'getElementById');
});

describe('with found element', () => {
  const taskform = taskformDiv(['pr1', 'pr2'], ['low', 'high']);

  beforeEach(() => {
    spy.mockReturnValue(taskform);
  });
....
}
```

2021-08-27 15:36 UTC, Ntwali-Josue commented on src/spec/todo-integration.test.js
> +    const browser = await puppeteer.launch();
**@henatan99 Thanks for pointing this out. We worked really hard on it, and learned a lot.**

2021-08-27 15:44 UTC, mricanho approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @enionsouza @Ntwali-Josue  🔥 

You worked hard in all the instructions that the previous Code Reviewers give you👍🏽 

Now you can merge this branch 🚀 

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-27 15:46 UTC, merged